# Generated by Django 6.0.6 on 2026-06-22 20:51

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Categoria"),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "cor_badge",
                    models.CharField(
                        default="#4B5563",
                        help_text="Código Hexadecimal para a cor no layout (Ex: #2563EB)",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FonteSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Fonte"),
                ),
                ("url_base", models.URLField(verbose_name="URL Base")),
            ],
        ),
        migrations.CreateModel(
            name="GabaritoAcHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NoticiaIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="VestibularHubPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AnuncioSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=255)),
                ("link", models.URLField()),
                (
                    "posicao",
                    models.CharField(
                        choices=[
                            ("topo_horizontal", "Banner Topo Horizontal (728x90)"),
                            ("lateral_feed", "Sidebar Lateral (300x250)"),
                            ("intercalado_cards", "Intercalado no Feed de Cards"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "imagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticiaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        help_text="Linha fina / Resumo que aparece abaixo do título principal."
                    ),
                ),
                (
                    "corpo",
                    wagtail.fields.StreamField(
                        [("paragrafo", 0), ("imagem", 1), ("citacao", 2)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                    ]
                                },
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                        },
                    ),
                ),
                (
                    "orgao_responsavel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Órgão Responsável (Edital)",
                    ),
                ),
                (
                    "numero_edital",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número do Edital",
                    ),
                ),
                (
                    "prazo_inscricao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inscrições Até"
                    ),
                ),
                (
                    "taxa_inscricao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Taxa R$",
                    ),
                ),
                (
                    "salario_ate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salários Até R$",
                    ),
                ),
                (
                    "link_pdf_oficial",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Link Oficial do Edital/Inscrição",
                    ),
                ),
                (
                    "status_edital",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aberto", "Aberto"),
                            ("encerrado", "Encerrado"),
                            ("prorrogado", "Prorrogado"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Status do Edital",
                    ),
                ),
                (
                    "gerado_por_ia",
                    models.BooleanField(default=False, verbose_name="Gerado por IA"),
                ),
                (
                    "fonte_original_url",
                    models.URLField(blank=True, verbose_name="URL da Fonte Original"),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, fica elegível para o topo da Home",
                    ),
                ),
                (
                    "destaque_ordem",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Ordem numérica no bloco Hero", null=True
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="noticias.categoriasnippet",
                    ),
                ),
                (
                    "fonte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="noticias.fontesnippet",
                    ),
                ),
                (
                    "imagem_capa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NoticiaPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="noticias.noticiapage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="noticiapage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="noticias.NoticiaPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
