# Generated by Django 6.0.6 on 2026-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anunciosnippet",
            name="posicao",
            field=models.CharField(
                choices=[
                    ("topo_horizontal", "Banner Topo Horizontal (728x90)"),
                    ("abaixo_mural", "Abaixo do Mural de Editais (728x90)"),
                    ("lateral_feed", "Sidebar Lateral (300x250)"),
                    ("intercalado_cards", "Intercalado no Feed de Cards"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="GabaritoAcHomePage",
        ),
    ]
