# Generated by Django 6.0.6 on 2026-06-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0002_alter_anunciosnippet_posicao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anunciosnippet",
            name="posicao",
            field=models.CharField(
                choices=[
                    ("topo_horizontal", "Banner Topo Horizontal (728x90) — Home"),
                    ("abaixo_mural", "Abaixo do Mural de Editais (728x90) — Home"),
                    ("topo_noticias", "Topo do Feed de Notícias (728x90)"),
                    ("lateral_feed", "Sidebar Lateral (300x250) — Notícias"),
                    ("intercalado_cards", "Intercalado no Feed de Cards"),
                ],
                max_length=50,
            ),
        ),
    ]
