# Generated by Django 6.0.6 on 2026-06-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0003_alter_anunciosnippet_posicao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticiapage",
            name="fonte_original_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL da Fonte Original"
            ),
        ),
        migrations.AlterField(
            model_name="noticiapage",
            name="link_pdf_oficial",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Link Oficial do Edital/Inscrição",
            ),
        ),
    ]
