# Generated by Django 6.0.6 on 2026-06-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0005_tornar_fonte_obrigatoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticiapage",
            name="revisado",
            field=models.BooleanField(
                default=False,
                help_text="Editais importados automaticamente só aparecem no mural da Home após revisão manual.",
                verbose_name="Revisado e Aprovado",
            ),
        ),
    ]
