# Generated by Django 6.0.6 on 2026-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_newsletterpage_newslettersignup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletterpage",
            options={
                "verbose_name": "Página WhatsApp",
                "verbose_name_plural": "Páginas WhatsApp",
            },
        ),
        migrations.AlterModelOptions(
            name="newslettersignup",
            options={
                "verbose_name": "Inscrição WhatsApp",
                "verbose_name_plural": "Inscrições WhatsApp",
            },
        ),
        migrations.RemoveField(
            model_name="newslettersignup",
            name="email",
        ),
        migrations.AddField(
            model_name="newslettersignup",
            name="whatsapp",
            field=models.CharField(
                help_text="Número com DDD, apenas números (ex: 5599999999999)",
                max_length=20,
                unique=True,
                verbose_name="WhatsApp",
            ),
            preserve_default=False,
        ),
    ]
