# Generated by Django 6.0.6 on 2026-06-23 15:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alterar_newsletter_para_whatsapp"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContatoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "corpo",
                    wagtail.fields.StreamField(
                        [("paragrafo", 0)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                    ]
                                },
                            )
                        },
                    ),
                ),
                (
                    "dpo_email",
                    models.EmailField(
                        default="dpo@gabaritoac.com.br",
                        help_text="E-mail para contato do Encarregado de Dados (LGPD Art. 41)",
                        max_length=254,
                        verbose_name="E-mail do DPO/Encarregado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato / DPO",
                "verbose_name_plural": "Contatos / DPO",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PoliticaPrivacidadePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "corpo",
                    wagtail.fields.StreamField(
                        [("paragrafo", 0), ("citacao", 1)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                    ]
                                },
                            ),
                            1: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Política de Privacidade",
                "verbose_name_plural": "Políticas de Privacidade",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="newslettersignup",
            name="consentimento",
            field=models.BooleanField(
                default=False,
                verbose_name="Autorizo o tratamento dos meus dados pessoais conforme a Política de Privacidade",
            ),
        ),
        migrations.AddField(
            model_name="newslettersignup",
            name="consentimento_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do consentimento"
            ),
        ),
    ]
